spring:
  application:
    name: joongo
  datasource:
    url: jdbc:mysql://localhost:3306/cedb2024
    username: root
    password: skdnjsgh99
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secretKey: SuperSecureKeyThatIsAtLeast64CharactersLongForHS512Algorithmababababababab

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    datasource:
      url: jdbc:mysql://localhost:3306/cedb2024
      username: ubuntu
      password: ${AWS_DATABASE_KEY}
      driver-class-name: com.mysql.cj.jdbc.Driver
    stack:
      auto: false
    s3:
      bucket: joonggo-bucket
      path:
        product: product

logging:
  level:
    org.apache.ibatis: DEBUG

# Test Token
#test-token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsImlhdCI6MTczMzMyMTgyNCwiZXhwIjoxNzMzMzI1NDI0fQ.m9PMJsloMBXrDNQJ6obtcpY2MHTAcA4VRrOfrzm7-O52ws2rQRADZwEvJ27kCp3zktRtgzWddKf56a7IzJ_QmA
